apiVersion: gateway.envoyproxy.io/v1alpha1
kind: ClientTrafficPolicy
metadata:
  name: proxy-protocol
  namespace: sealed-secrets
spec:
  proxyProtocol:
    optional: true
  targetRefs:
    - group: gateway.networking.k8s.io
      kind: Gateway
      name: sealed-secrets
