apiVersion: v1
kind: Service
metadata:
  name: browserless-chrome
  namespace: browserless-chrome
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: http
  selector:
    app: browserless-chrome
