[hololens]
package = "holo/lens-helm3/1.3"

[hololens.input]
root = "chime"
files = "**"

[hololens.output]
merge = "replace"

[hololens.helm]
namespace = "chime"
release_name = "chime"

chart_path = "helm-chart"
value_files = [
    "release-values.yaml"
]
