[hololens]
container = "ghcr.io/hologit/lenses/helm3:latest"

[hololens.input]
root = "chime"
files = "**"

[hololens.output]
merge = "replace"

[hololens.helm]
namespace = "chime"
release_name = "chime"

chart_path = "helm-chart"
value_files = [
    "release-values.yaml"
]
