[hololens]
package = "holo/lens-helm3/1.3"

[hololens.input]
root = "code-for-philly"
files = "**"

[hololens.output]
merge = "replace"

[hololens.helm]
namespace = "code-for-philly"
release_name = "code-for-philly"

chart_path = "helm-chart"
value_files = [
    "release-values.yaml"
]
