[hololens]
container = "ghcr.io/hologit/lenses/helm3:latest"

[hololens.input]
root = "squadquest-supabase"
files = "**"

[hololens.output]
merge = "replace"

[hololens.helm]
namespace = "squadquest-supabase"
release_name = "squadquest-supabase"
namespace_fill = true

chart_path = "helm-chart"
value_files = [
    "release-values.yaml"
]
