# See: https://github.com/supabase-community/supabase-kubernetes/blob/main/charts/supabase/values.yaml

secret:
  jwt:
    secretRef: jwt
  smtp:
    secretRef: postmark
  dashboard:
    secretRef: dashboard
  db:
    secretRef: postgres
  analytics:
    secretRef: logflare
  s3:
    secretRef: linode-storage

db:
  enabled: true
  image:
    tag: 15.6.1.143
  livenessProbe:
    exec:
      command:
        - pg_isready
        - -U
        - postgres
    initialDelaySeconds: 3

studio:
  image:
    tag: 20241111-d7c6eb1

auth:
  image:
    tag: v2.164.0
  environment:
    API_EXTERNAL_URL: https://squadquest-supabase.live.k8s.phl.io
    GOTRUE_SITE_URL: https://squadquest-supabase.live.k8s.phl.io
    GOTRUE_EXTERNAL_EMAIL_ENABLED: "true"
    GOTRUE_SMTP_ADMIN_EMAIL: "admin@squadquest.app"
    GOTRUE_SMTP_HOST: "smtp.postmarkapp.com"
    GOTRUE_SMTP_PORT: "587"
    GOTRUE_SMTP_SENDER_NAME: "auth@squadquest.app"


rest:
  image:
    tag: v12.2.3

realtime:
  image:
    tag: v2.33.61
  livenessProbe:
    httpGet:
      path: /
      port: 4000
    initialDelaySeconds: 3

meta:
  image:
    tag: v0.84.3

storage:
  image:
    tag: v1.13.3
  environment:
    STORAGE_BACKEND: s3
    GLOBAL_S3_BUCKET: squadquest-supabase-storage
    GLOBAL_S3_ENDPOINT: us-east-1.linodeobjects.com
    GLOBAL_S3_PROTOCOL: https
  livenessProbe:
    httpGet:
      path: /status
      port: 5000
    initialDelaySeconds: 3
  persistence:
    enabled: false

imgproxy:
  image:
    tag: v3
  environment:
    IMGPROXY_ENABLE_WEBP_DETECTION: "true"
  livenessProbe:
    exec:
      command:
        - imgproxy
        - health
    initialDelaySeconds: 3

kong:
  image:
    tag: 2.8.5

analytics:
  image:
    tag: 1.10.0
  livenessProbe:
    httpGet:
      path: /health
      port: 4000
    initialDelaySeconds: 3

vector:
  image:
    tag: 0.42.X-alpine
  livenessProbe:
    httpGet:
      path: /health
      port: 9001
    initialDelaySeconds: 3
  ## Vector requires logs from the control plane to function.
  ## This is normally stored in /var/log/pods
  ## Modify these values according to your environment.
  volumeMounts:
    - name: pod-logs
      mountPath: /var/log/pods
  volumes:
    - name: pod-logs
      hostPath:
        path: /var/log/pods

functions:
  image:
    tag: v1.65.3
