apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/instance: code-for-philly
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: code-for-philly
    app.kubernetes.io/version: 1.0.0
    helm.sh/chart: emergence-site-1.0.0
  name: code-for-philly-site
  namespace: code-for-philly
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
  selector:
    app.kubernetes.io/instance: code-for-philly
    app.kubernetes.io/name: code-for-philly
