apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: squadquest-supabase-reader
rules:
  - apiGroups:
      - ''
    resources:
      - nodes
      - namespaces
      - pods
    verbs:
      - list
      - watch
  - apiGroups:
      - ''
    resourceNames:
      - squadquest-supabase-*
    resources:
      - pods/log
    verbs:
      - get
