apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/instance: squadquest-supabase
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: supabase
    helm.sh/chart: supabase-0.1.3
  name: squadquest-supabase-supabase-rest
  namespace: squadquest-supabase
spec:
  selector:
    matchLabels:
      app.kubernetes.io/instance: squadquest-supabase
      app.kubernetes.io/name: supabase-rest
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: squadquest-supabase
        app.kubernetes.io/name: supabase-rest
    spec:
      containers:
        - env:
            - name: DB_DRIVER
              value: postgres
            - name: DB_PORT
              value: '5432'
            - name: DB_SSL
              value: disable
            - name: DB_USER
              value: authenticator
            - name: PGRST_APP_SETTINGS_JWT_EXP
              value: '3600'
            - name: PGRST_DB_ANON_ROLE
              value: anon
            - name: PGRST_DB_SCHEMAS
              value: public,storage,graphql_public
            - name: PGRST_DB_USE_LEGACY_GUCS
              value: 'false'
            - name: DB_HOST
              value: squadquest-supabase-supabase-db
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: password
                  name: postgres
            - name: DB_PASSWORD_ENC
              valueFrom:
                secretKeyRef:
                  key: password
                  name: postgres
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  key: database
                  name: postgres
            - name: PGRST_DB_URI
              value: >-
                $(DB_DRIVER)://$(DB_USER):$(DB_PASSWORD_ENC)@$(DB_HOST):$(DB_PORT)/$(DB_NAME)?sslmode=$(DB_SSL)
            - name: PGRST_JWT_SECRET
              valueFrom:
                secretKeyRef:
                  key: secret
                  name: jwt
            - name: PGRST_APP_SETTINGS_JWT_SECRET
              valueFrom:
                secretKeyRef:
                  key: secret
                  name: jwt
          image: postgrest/postgrest:v12.2.3
          imagePullPolicy: IfNotPresent
          name: supabase-rest
          ports:
            - containerPort: 3000
              name: http
              protocol: TCP
          securityContext: {}
      securityContext: {}
      serviceAccountName: squadquest-supabase-supabase-rest
