apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/instance: squadquest-supabase
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: supabase
    helm.sh/chart: supabase-0.1.3
  name: squadquest-supabase-supabase-studio
  namespace: squadquest-supabase
spec:
  selector:
    matchLabels:
      app.kubernetes.io/instance: squadquest-supabase
      app.kubernetes.io/name: supabase-studio
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: squadquest-supabase
        app.kubernetes.io/name: supabase-studio
    spec:
      containers:
        - env:
            - name: NEXT_ANALYTICS_BACKEND_PROVIDER
              value: postgres
            - name: NEXT_PUBLIC_ENABLE_LOGS
              value: 'true'
            - name: STUDIO_DEFAULT_ORGANIZATION
              value: Default Organization
            - name: STUDIO_DEFAULT_PROJECT
              value: Default Project
            - name: STUDIO_PORT
              value: '3000'
            - name: SUPABASE_PUBLIC_URL
              value: 'http://example.com'
            - name: SUPABASE_URL
              value: 'http://squadquest-supabase-supabase-kong:8000'
            - name: STUDIO_PG_META_URL
              value: 'http://squadquest-supabase-supabase-meta:8080'
            - name: SUPABASE_ANON_KEY
              valueFrom:
                secretKeyRef:
                  key: anonKey
                  name: squadquest-supabase-jwt
            - name: SUPABASE_SERVICE_KEY
              valueFrom:
                secretKeyRef:
                  key: serviceKey
                  name: squadquest-supabase-jwt
            - name: LOGFLARE_URL
              value: 'http://squadquest-supabase-supabase-analytics:4000'
            - name: LOGFLARE_API_KEY
              valueFrom:
                secretKeyRef:
                  key: apiKey
                  name: squadquest-supabase-analytics
          image: 'supabase/studio:20241111-d7c6eb1'
          imagePullPolicy: IfNotPresent
          name: supabase-studio
          ports:
            - containerPort: 3000
              name: http
              protocol: TCP
          securityContext: {}
      securityContext: {}
      serviceAccountName: squadquest-supabase-supabase-studio
