# These values are applied last as downstream overrides
# Defaults: https://github.com/gissilabs/charts/blob/master/vaultwarden/values.yaml
# Documentation: https://github.com/gissilabs/charts/tree/master/vaultwarden#helm-chart

ingress:
  enabled: true
  host: vaultwarden.phl.io
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-prod
  tls:
    - secretName: vaultwarden-tls
      hosts:
        - vaultwarden.phl.io

vaultwarden:
  domain: https://vaultwarden.phl.io
  smtp:
    enabled: true
    host: smtp.postmarkapp.com
    from: support@codeforphilly.org
    existingSecret: smtp-postmark
  admin:
    enabled: true
    existingSecret: admin-token
