apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/instance: code-for-philly
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: code-for-philly
    app.kubernetes.io/version: 1.0.0
    helm.sh/chart: emergence-site-1.0.0
  name: code-for-philly
  namespace: code-for-philly
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: code-for-philly
      app.kubernetes.io/name: code-for-philly
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: code-for-philly
        app.kubernetes.io/managed-by: Helm
        app.kubernetes.io/name: code-for-philly
        app.kubernetes.io/version: 1.0.0
        helm.sh/chart: emergence-site-1.0.0
    spec:
      containers:
        - env:
            - name: HAB_LICENSE
              value: accept-no-persist
            - name: HAB_SITE_COMPOSITE
              value: |
                [services.mysql]
                pkg_ident = "core/mysql"
            - name: HAB_SITE
              value: |
                default_timezone = "America/New_York"

                [sites.default]
                handle = "code-for-philly"
                  primary_hostname = "codeforphilly.org"
                  title = "Code for Philly"

                [core]

                [limit]
                  memory = "200M"
                  post = "200M"
                  execution_time = "30"

                [cache]
                  size = "512M"
            - name: HAB_MYSQL
              value: |
                app_username = "admin"
                app_password = "admin"
                bind = "0.0.0.0"
          envFrom:
            - secretRef:
                name: discourse
            - secretRef:
                name: email
            - secretRef:
                name: github
            - secretRef:
                name: mailchimp
            - secretRef:
                name: recaptcha
            - secretRef:
                name: saml2
            - secretRef:
                name: slack
          image: 'ghcr.io/codeforphilly/codeforphilly.org/site-composite:1.3.8'
          imagePullPolicy: Always
          name: code-for-philly-site
          ports:
            - containerPort: 80
              name: http
              protocol: TCP
            - containerPort: 3306
              name: mysql
              protocol: TCP
          resources:
            limits: {}
            requests:
              memory: 300Mi
          volumeMounts:
            - mountPath: /hab/svc/site/data
              name: code-for-philly-site
              subPath: data
            - mountPath: /hab/svc/mysql/data
              name: code-for-philly-database
              subPath: data
      restartPolicy: Always
      securityContext:
        fsGroup: 42
      volumes:
        - name: code-for-philly-site
          persistentVolumeClaim:
            claimName: code-for-philly-site
        - name: code-for-philly-database
          persistentVolumeClaim:
            claimName: code-for-philly-database
