apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ include "vaultwarden.fullname" . }}-legacy
  labels:
    {{- include "vaultwarden.labels" . | nindent 4 }}
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/permanent-redirect: 'https://vaultwarden.phl.io$request_uri'
spec:
  rules:
    - host: bitwarden.phl.io
      http:
        paths:
          - path: /
            backend:
              serviceName: vaultwarden
              servicePort: 80

  tls:
    - secretName: bitwarden-tls
      hosts:
        - bitwarden.phl.io

