apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/permanent-redirect: 'https://vaultwarden.phl.io$request_uri'
    nginx.ingress.kubernetes.io/rewrite-target: /
  labels:
    app.kubernetes.io/instance: vaultwarden
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: vaultwarden
    app.kubernetes.io/version: 1.23.0
    helm.sh/chart: vaultwarden-0.5.1
  name: vaultwarden-legacy
  namespace: vaultwarden
spec:
  rules:
    - host: bitwarden.phl.io
      http:
        paths:
          - backend:
              serviceName: vaultwarden
              servicePort: 80
            path: /
  tls:
    - hosts:
        - bitwarden.phl.io
      secretName: bitwarden-tls
