apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    kubernetes.io/ingress.class: nginx
  labels:
    app.kubernetes.io/instance: vaultwarden
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: vaultwarden
    app.kubernetes.io/version: 1.23.0
    helm.sh/chart: vaultwarden-0.5.1
  name: vaultwarden
  namespace: vaultwarden
spec:
  rules:
    - host: vaultwarden.phl.io
      http:
        paths:
          - backend:
              service:
                name: vaultwarden
                port:
                  number: 3012
            path: /notifications/hub
            pathType: Prefix
          - backend:
              service:
                name: vaultwarden
                port:
                  number: 80
            path: /
            pathType: Prefix
  tls:
    - hosts:
        - vaultwarden.phl.io
      secretName: vaultwarden-tls
