apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/permanent-redirect: https://vaultwarden.phl.io$request_uri
    nginx.ingress.kubernetes.io/rewrite-target: /
  labels:
    app.kubernetes.io/instance: vaultwarden
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: vaultwarden
    app.kubernetes.io/version: 1.32.7
    helm.sh/chart: vaultwarden-1.2.5
  name: vaultwarden-legacy
  namespace: vaultwarden
spec:
  rules:
    - host: bitwarden.phl.io
      http:
        paths:
          - backend:
              service:
                name: vaultwarden
                port:
                  number: 80
            path: /
            pathType: Prefix
  tls:
    - hosts:
        - bitwarden.phl.io
      secretName: bitwarden-tls
