apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/proxy-cache-bypass: $http_upgrade
    nginx.ingress.kubernetes.io/proxy-http-version: '1.1'
    nginx.ingress.kubernetes.io/proxy-set-header-connection: upgrade
    nginx.ingress.kubernetes.io/proxy-set-header-host: $host
    nginx.ingress.kubernetes.io/proxy-set-header-upgrade: $http_upgrade
  name: browserless-chrome
  namespace: browserless-chrome
spec:
  rules:
    - host: browserless-chrome.live.k8s.phl.io
      http:
        paths:
          - backend:
              service:
                name: browserless-chrome
                port:
                  number: 80
            path: /
            pathType: Prefix
  tls:
    - hosts:
        - browserless-chrome.live.k8s.phl.io
      secretName: browserless-chrome-tls
