apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: balancer-db-credentials
  namespace: cloudnative-pg
spec:
  encryptedData:
    password: >-
      AgBcEHUAKYZitDG0dG2GbhGvxXVfjKzPnSa1OEsG+TPEdqfIEp92huTUEQeHPoABZ0MtzlHASkZiU4xvMdUoGlaMKqP+XWS2Ks8VKXyLvsL5Xdh8yDBhezgi13hN5ELu9fx8kkbds3bYhsz8+WPOu6vUpSpehOQ+Qfdy5LvA+FZUL93Ks0eZGxgYwSBzPLc0m70QiQ7ocyqpExSoFXYvIDWo6UGk1FHr/8nSgA5gA5XrrjZT+fD4lRzWSxKDEnEHGZPXQtvvLizg0G7rD4aoemySLvDlPDlMQ/r7WAXlMHpxgFJsM/TRGH8R7eyhtTfb+u0NmkNUvDV5yCEosEG17gGTOyIEDxxGTS5/kttAUthBoqq+3ugOiZDr0QpLNCregie9Fu12E7E32sUYNH+ITj7wh61N4LM6/GlCE3cFnEB07btbQeaB54/aVJt0rDcIU5Kg/chGhg3g/Wt8CHi0s2LCxjIzBcPKfD4T1TM+84h5tnF+H5k2PqsjtUR+kbrXtHA0E7noHzcrUYY3bK7dAZQlj/bzYtA9gwFzMsR+94wrfucRnu81wjHBn4altMkzzAStDfIRsl2m+j44V4U94gkrUtoUjp/Ffd5TIRjb3ymioRrlsKdjfdSFOdcybYI/rF7b9WoH5fjDoNS7s6qdszA93HYj0rdnghqW3m7ql8Rylx0VwRJn4yTEJ4YIs2/CyJiKF5VcwzgCbt78SqF8CtIkZNfwA8TykeSkyATjyna7ZqKAdS1tG0Qm
    username: >-
      AgBmC/873NnIntMIFo6VKrcAjsbKAecDwJpbGyRZ5bRwTQxbGWTwm3PTOL5hoMbINlEdLp8/T+1wCxaVHlA6GrMjmVqUIAxOuOLlKNeGH5uDVJ6xu7AD0MGOgyqYPqiKwMpJz9r8aYEmKJ1WlX/BKgYvgsOZ9IuNaopqxvGYQAyGh2du1aRicXveYcfnLcomIWjNpv+KV5avtg0B1MF5aZIVAOeVBqCuhQnyK3WjzB6YytSR1s4igCqx2C8n7zm4JKdHBYCw9faVsF8aKfc5cQqomdvOesnCmKy/bZWG6M+9Zx/3iO/HCsjiQZutDiME2f0G8ff0wzW3/OL/4FRfQpDarqUfT5FXrsEYpc7Rj/pok8ZbqdHo+2RHrh0nwMG9gZShhyXVsq2kCyh61DsEZQRZpJsdKz24j3Sf7qzD1XhUPZKZT/lKC7lcdFgKDNSY0bcUgv+/GDzkOLdkJE14fnS4dpcGe3fNGC6JJru8VPFXjQ32zWGvpt8gVFOOlb8hqQmHY52/Di9SvHJ/r5bHuiP23Ih/O6bAVWRgk91BbmNe9QAyMN0Q1LgYzjjIsnLjQsImmzTGGjGH4yLcZa3HKXGGD5GR1RfERVfIixgX/tRlS1/essRZxQrpdJou1yhY7+BFMDgHZCEMK36Xb/B4fIAnAx4KlhKGbjbJCicJkJVTEx6WWFGDifAnmeRApPE0S5PQiYYutUnhPw==
  template:
    metadata:
      name: balancer-db-credentials
      namespace: cloudnative-pg
    type: kubernetes.io/basic-auth
