apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/instance: chime
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: chime
    app.kubernetes.io/version: 1.0.0
    helm.sh/chart: chime-0.1.0
  name: chime
  namespace: chime
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: chime
      app.kubernetes.io/name: chime
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: chime
        app.kubernetes.io/name: chime
    spec:
      containers:
        - image: ghcr.io/codeforphilly/chime/penn-chime:1.1.5
          imagePullPolicy: IfNotPresent
          livenessProbe:
            httpGet:
              path: /
              port: http
          name: chime
          ports:
            - containerPort: 8000
              name: http
              protocol: TCP
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources: {}
          volumeMounts:
            - mountPath: /mnt/google-api-creds
              name: google-api-creds
              readOnly: true
      imagePullSecrets:
        - name: regcred
      volumes:
        - name: google-api-creds
          secret:
            secretName: google-api-creds-json
