apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app.kubernetes.io/component: postgresql
    app.kubernetes.io/instance: third-places
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: third-places
    app.kubernetes.io/version: 0.1.2
    helm.sh/chart: third-places-0.1.0
  name: third-places-postgresql
  namespace: third-places
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/component: postgresql
      app.kubernetes.io/instance: third-places
      app.kubernetes.io/name: third-places
  serviceName: postgresql
  template:
    metadata:
      labels:
        app.kubernetes.io/component: postgresql
        app.kubernetes.io/instance: third-places
        app.kubernetes.io/name: third-places
    spec:
      containers:
        - envFrom:
            - secretRef:
                name: postgresql
          image: postgis/postgis:13-3.1
          livenessProbe:
            initialDelaySeconds: 15
            periodSeconds: 20
            tcpSocket:
              port: 5432
          name: postgresql
          ports:
            - containerPort: 5432
              name: postgresql
          readinessProbe:
            initialDelaySeconds: 5
            periodSeconds: 10
            tcpSocket:
              port: 5432
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: data
              subPath: postgresql-data
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 5Gi
