apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    kubernetes.io/ingress.class: nginx
  name: echo-http
  namespace: echo-http
spec:
  rules:
    - host: echo-http.live.k8s.phl.io
      http:
        paths:
          - backend:
              service:
                name: echo-http
                port:
                  number: 80
            path: /
            pathType: Prefix
  tls:
    - hosts:
        - echo-http.live.k8s.phl.io
      secretName: echo-http-tls
