apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: pac-api
  namespace: choose-native-plants
spec:
  encryptedData:
    PAC_API_BASE_URL: >-
      AgAnn70pH2dXDh7H0trpwUKRtPG1SEpl2L/Ql4HCLcpHhzsbqSGLRGnaTSyvuzQ9/PZ0fxFDI/cm9/WsRChkxHEzet4vTtoFpXloRhc6hym/6W5pllR531GaBvUVlxp+1JUOTUC8D7eeXTvhiiZjvbrKgfkaLdnAiOU434Vk43SGt2yzJBxyWTvWgth+joV77grCYvU8keTcSLJbRoWEZ/CLqXwI9ECI5As7hThkHCMviArB0GPJqPMaNtn1Su4j3Wv+ewlDl2i8jXoyrlU3tJFHx9QEM7ssOXR+6TeVFDb42Mj4oyIQIXiAb4ikgqTPxC6iuYh7lwtMkT8EIOQYMFJwXnNWhpR1phZWWM9VqGoHITZyCCCU+VcORQVFAjfqjD6u6PBlD71c9+ChMihNEu8WhavCVQzUDaoZSB9mcim8dBZxr+7FJ9e91nKfPToEArKb6Dk57r4m3+lZUn6LUl364i3R/3EB0/gjyyjstucuwKnRcOH2ajKAhxSqpvlT7p+KleS9nJqlejpiZNzsaxR4P+lAN3urq4Zt+ki18UjZro6D5Ryv81SvLwCHbWEc7/2RTQe5emnmhtljkBStIrUYWuZL64+UWxv63IXohhWTHH62WBXeflokJ0UEecI2Igm8bv9diEQPbiGp08Dr56RXbnMldPWBQ61WPQBo+U5Iu3KRkK6jWOI+xj3EFTUmw4UdqJQ53XFaDSn8+AY7lXbvuiRApgEz06VzBu0=
    PAC_API_KEY: >-
      AgAgj+WeUKXuA2xGbR9k7YIYvC/2QrJV3SF/PN+HHlFdK8PjDkU/cQjUN57+CgUXtCxjPYjE7QHOyb0P1qyqia/Ralx2Mp9vP2B392zO1wY4rtqU6pSLG7Bpy/MKVEmBek+4H2MYazM389CzkdNRZ+ReaqE4OcuqA9rDKUnT0G/esd0n7sX7bchX9EVqDy3E5fkaB9hYZ6vZHxeM+V9ZN1NRuENqRqMFAkpAofMDA/v8ItZSNKXusuz402LBhgjXQOnAD3S8B/CmjG4h5NrMA4FqRoniFhsWMXb4on5wlZEi2106iJG8dQmfFVXUKdPCFfVjz0lWYw2FmLSDbkriuDUhtoxaYy14z7P1PvjvTKOIF5kv+ZeKaMrOq4vl/hgrg5EcBC6yfvoDJgfb3VV9Bu0An3sH6ri9WNTuWB+3IEbxoZ7yMML+zEtCC/D4CI+2XE6kUxMSx3mmDLm3g5MOq3JWxoZg/bjjV3xErhehABBIUzTcSRTipwM3b9DO1j2vBTmkMBfsOtpTS1p9vjxbDrM1TgFeA/KxnpvgkYKwsLnXOglrs8DP/kiB4kj4WB/rANGhPNFXkAKXrHMPBXzyKITSNf0kDQMQnVI2TBqTZvwkaitOd9DO/UW6f/1DgwpZR/iwX+sS9RrZ0VTQTkoKMY29BYI9JKsgMbDvdRceKo5vBebXx/8mJrNEKF0t1wJv3TkmI3adXpZ74qXwK1wjEk9+ihoRoEl3G1DdIL5EHyma4q9wPuM=
  template:
    metadata:
      creationTimestamp: null
      name: pac-api
      namespace: choose-native-plants
    type: Opaque
