---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: smtp-postmark
  namespace: grafana
spec:
  encryptedData:
    smtp-password: AgC4T5M9UXwypdnV/UszylDTaVofFB9kqoEf1b5BBeb8C+KJ7DF1/uDKpGgjY5yBvEzhvGYHDguKCONyxk+0sCe6XnEb7QpvpyG3u1zpIvOgQnRVgNRG+2o5V/0cT8MPG6nOuh9bZu3n1k0i08oeVyzeYY87Zs14SledM1rP05eUrTgYxNhuPUzAZEqS86+nMj+S+87wgt6e0TTdTzoF4TkmV6oGHQbbGwMBVQ7ZkKaZ1dAGahr33+crPtmoZ3ePrFuGbmawAGzaFKW3vTTsSeFeId1bOzpPgUkvvXzURadaSZfk6d6Coy738HnM15qgdsb+a9hlyGrHtHEJK1AHzr+FO246zzxYTeGId75ElhqPnboSy6QsxGohFWu/TFWUFvJFUcrHkbYnthiTZ3Z0AMe9ah+u9EzXgNTzcw2v/vV+hOX9YaelQ3TcWiTAMsyK8MSfMg8wgzBMlHZjTDZRo205QTqYanYHHf1ndcXFApEDrTVyULbRtRZZIschbsJBg4v5Qs5OAVLL43uRwZNBUGPqSr77dQpWfjAhgzPhAh2JB1Ots8vBurwrUa/ENLciE3EK6Q8tSrn8d7ojU+IMAceiu0vnbsvnSleK0e87PnqKL4bBJ0u2RLOT8SyUECCE596aUB2qGpWGiYQRBysF4KvutNRIQegowslGROJ4CersncUzZQ07t1hzgUYDXq+Vl5SKaw27AKtkPZz7lAalSHgMGaaHjYyseT+Fas1tidaWR/mO2h8=
    smtp-user: AgB3oKCpgdCwiIT5izzo9QL1UWC7BgPTXoCFa40zr/P3N+Wrd5GZENoMSMMygI/rCxIbilTqdx3V6/EjMgTQuGviVTVlIblfaoeuaiwJFVJGRrzY98+TMktAfZB+v+FCc92+P6pJeAsYwhwPh96ZQVuKlRd1857cjdS19RUEYZQFuTbJvIpLNWVEsPayTd1n1yr6X4qPWHf3QnC5HKeAf65wvThFrxb+cIm1Fgf0zeTK+AwHnA9ZbvwedyWz4oULs+AmrGcE/f1mhj7EJDpp36qDsVRpASstgCNGzfglCbl3gAT136j7RfVCcl1d8mjNT8ZSakA9YpJzjw5sHxB5ITXZpvm5uNbWRgH/DjLxpsaEISJEZRVSTMEULxK0Kb/IOzKk11NHzWvGk+Wm51jZpBYisdGe3/eWITu/Q3Xoqq4ESGCfhIxotc7L75equWijmcCXZTKER2EE8vIERkoteZt6GMbumtGx6Nr5Q6xs9dW6QnWclO66FP4OhiXbRw5MHngtdzBhHBlx3YIpJbrsaL6f12j3ecdaNRLtgy5UvcL8qHhH2EdS2xqLlzI9iQz6lwJe7/WPsLE23uiOUI6zg9G1vdJ24dCOzMywBehR3CANA+N3FbbYHHaasv+1/Sd1O4cHHy7aonQdVdu4832tZq6uPksw6wzL9t+fCQPffzDzFf5ZerLAfMeF1+I1wsRRqoX2Enf933b6vhDMQebaMxjlAvxRcnyU0phOMqTQ7f3G5TN/GrY=
  template:
    metadata:
      name: smtp-postmark
      namespace: grafana
    type: Opaque
