apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/instance: vaultwarden
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: vaultwarden
    app.kubernetes.io/version: 1.23.0
    component: postgresql
    helm.sh/chart: vaultwarden-0.5.1
  name: vaultwarden-postgresql
  namespace: vaultwarden
spec:
  ports:
    - name: postgresql
      port: 5432
  selector:
    app.kubernetes.io/instance: vaultwarden
    app.kubernetes.io/name: vaultwarden-postgresql
  type: ClusterIP
