---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: codeforphilly-data-deploy-key
  namespace: codeforphilly-ng
spec:
  encryptedData:
    id_ed25519: AgB9qEE7dyKORCuvvXx2i5vKhfEIsl//YP4EgEogtbVWlKPmUWQCyAUYvT2+kz1Qtt/DSHYT5XgnJ3OSeEqfaBFKkqtysch31/wJJOS+vXVVCsBCPWek3cno8CnG1wqmtGlziTIEQC5480lV3sgnvSsnIOlkt7Yc76HIuaUZj6Yw5CCOCTIidJLI+pYVoZPYlXPNj0Vk9sprnUnmOZuyJxAIcnAHzqP8QenfKpNI/hczr10MPNKMnc12NtsUtZH2tmDry4aj120RdEVTwyz4KHGMypBcJVs5U6wU4V4LWDOwXrFTs8aZzxRsXKup4KzxAU4xEXCQI+HY1aeS4cy1t4dj5zracoFs3cjgmsuJdVcW40/9T9Tr3AmHGmJzXxo2OtY97w9R+0enaqrQzaPdh3qDpqjnxC6Yuf0N4OmU6X4ZNbGu/p/SHHMSbNHgL/MDuaspG+R3a8N0wBze96Lw1z1CGJN1Z/iOpkcwQzE8HdGhbvOFYzzo1+sTejNXXke4JnC+fyuSzOg1Io5OiY9mJZ5xIx34VQxP0cNVRtWJtC4j/iAYBtlR7XKLpht/paWZLjWkhZl0PGatoySCWJQbEXC4AuIYlbSTv+6ONBBURmf6Qu0CZPKrf+PUNwRJCgrP+kO9smW8DphfVCdRXfa0rqe98dHwXsplEvmCdjjbXmX50CdL9UPMG8N4Ddg8ktrzvjZK1fCyX4K/FRC1OdriQ0ZvFVc2X32NMm4FUqK3PrvqESVOq6Ve6cCNl0emI393DVxVNVdEGUH8WA7Nhoxrn3i9BV1wy76ZwmNgeKLw0f6em4luMECl26FT4oF+7hx0PHfpN7m9R6AgPDKPkFRTt2sNTI/U2UKlWSxAUseM6Ae3jQ0msP+MIgRwiUAo6akXqFQr2DlvjNee4n4HfUFMpbUIuen9pMQKXoTZigkHpwto2KmXG4KaEEFV5524EZgZRK3i62nCiQIT+9uj2X3u7ObmdyHm4XXOKPu4SasvKuVUe3C+DQpT1xyNbmINH5Og1iSvCMioE+WYDfEFU1NsP6iic9jOZ8NkMsWvkaLYhdF95FV7iWa5mHlg+lvQDSLBQ0cLpoFhaE0Fdb8NZ+Qs1XDBIOfqI5k8U7LY6qVSa927Q4dg6yL3S0skC0xdgJWXETYhZRgpeCf9nmOPJcjyzrnzL2y4XBTBqKiyOm9BqlkN30iFFaF4pz/fDc8UBAggSy0vQfy963Ilkj5xLQsZgFWrVMSuV3FagxZMrYkRYG2PlqXtmtC/+ARkRK6eBEzJDso=
  template:
    metadata:
      name: codeforphilly-data-deploy-key
      namespace: codeforphilly-ng
