site:
  name: code-for-philly
  title: "Code for Philly"
  canonicalHostname: codeforphilly.org
  secondaryHostnames:
    - www.codeforphilly.org
    - codeforphilly.com
    - www.codeforphilly.com

  image:
    repository:
    tag: 1.0.3

ingress:
  enabled: true

volumes:
  site: 10Gi
  database: 15Gi

backups:
  enabled: true
  snitchUrl: "https://nosnch.in/7083177ce3"

hab:
  license: accept-no-persist
