site:
  name: code-for-philly
  title: "Code for Philly"
  canonicalHostname: codeforphilly.live.k8s.phl.io
  # canonicalHostname: codeforphilly.org

  image:
    repository: ghcr.io/codeforphilly/codeforphilly.org/site-composite
    tag: 1.1.11

  secrets:
    - name: 'discourse'
    - name: 'email'
    - name: 'github'
    - name: 'mailchimp'
    - name: 'recaptcha'
    - name: 'saml2'
    - name: 'slack'

ingress:
  enabled: true
  # secondaryHostnames:
  #   - www.codeforphilly.org
  #   - codeforphilly.com
  #   - www.codeforphilly.com

volumes:
  site: 10Gi
  database: 15Gi

backups:
  enabled: true
  snitchUrl: "https://nosnch.in/7083177ce3"

hab:
  license: accept-no-persist
