site:
  name: code-for-philly
  title: "Code for Philly"
  canonicalHostname: codeforphilly.org
  # canonicalHostname: codeforphilly.live.k8s.phl.io

  image:
    repository: ghcr.io/codeforphilly/codeforphilly.org/site-composite
    tag: 1.1.16

  secrets:
    - name: 'discourse'
    - name: 'email'
    - name: 'github'
    - name: 'mailchimp'
    - name: 'recaptcha'
    - name: 'saml2'
    - name: 'slack'

ingress:
  enabled: true
  secondaryHostnames:
    - codeforphilly.live.k8s.phl.io
    - www.codeforphilly.org
    # using URL Redirects at the registrar level for now:
    # - codeforphilly.com
    # - www.codeforphilly.com

volumes:
  site: 10Gi
  database: 15Gi

backups:
  enabled: true
  snitchUrl: "https://nosnch.in/7083177ce3"

hab:
  license: accept-no-persist
