---
kind: Namespace
apiVersion: v1
metadata:
  name: "chime"
---
# Source: chime/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: chime
  namespace: chime
  labels:
    helm.sh/chart: chime-0.1.0
    app.kubernetes.io/name: chime
    app.kubernetes.io/instance: chime
    app.kubernetes.io/version: "1.0.0"
    app.kubernetes.io/managed-by: Helm
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: chime
    app.kubernetes.io/instance: chime
---
# Source: chime/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: chime
  namespace: chime
  labels:
    helm.sh/chart: chime-0.1.0
    app.kubernetes.io/name: chime
    app.kubernetes.io/instance: chime
    app.kubernetes.io/version: "1.0.0"
    app.kubernetes.io/managed-by: Helm
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: chime
      app.kubernetes.io/instance: chime
  template:
    metadata:
      labels:
        app.kubernetes.io/name: chime
        app.kubernetes.io/instance: chime
    spec:
      imagePullSecrets:
        - name: regcred
      containers:
        - name: chime
          image: "docker.pkg.github.com/codeforphilly/chime/penn-chime:1.1.5"
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8000
              protocol: TCP
          volumeMounts:
            - name: google-api-creds
              mountPath: "/mnt/google-api-creds"
              readOnly: true
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
            {}
      volumes:
        - name: google-api-creds
          secret:
            secretName: google-api-creds-json
---
# Source: chime/templates/ingress.yaml
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: chime
  namespace: chime
  labels:
    helm.sh/chart: chime-0.1.0
    app.kubernetes.io/name: chime
    app.kubernetes.io/instance: chime
    app.kubernetes.io/version: "1.0.0"
    app.kubernetes.io/managed-by: Helm
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/configuration-snippet: |
      # Inject Google Tag Manager:
    
      proxy_set_header Accept-Encoding ""; # upstream compression must be disabled
    
      sub_filter '</head>' '<script>(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({"gtm.start": new Date().getTime(),event:"gtm.js"});var f=d.getElementsByTagName(s)[0], j=d.createElement(s),dl=l!="dataLayer"?"&l="+l:"";j.async=true;j.src="https://www.googletagmanager.com/gtm.js?id="+i+dl;f.parentNode.insertBefore(j,f); })(window,document,"script","dataLayer","GTM-KBZ6ZKX");</script></head>';
    
      sub_filter '</body>' '<noscript><iframe src="https://www.googletagmanager.com/ns.html?id=GTM-KBZ6ZKX" height="0" width="0" style="display:none;visibility:hidden"></iframe></noscript></body>';
    nginx.ingress.kubernetes.io/proxy-body-size: "0"
spec:
  tls:
    - hosts:
        - "penn-chime.phl.io"
        - "penn-chime.live.k8s.phl.io"
      secretName: penn-chime-tls
  rules:
    - host: "penn-chime.phl.io"
      http:
        paths:
          - path: /
            backend:
              serviceName: chime
              servicePort: 80
    - host: "penn-chime.live.k8s.phl.io"
      http:
        paths:
          - path: /
            backend:
              serviceName: chime
              servicePort: 80
