apiVersion: batch/v1
kind: Job
metadata:
  annotations:
    helm.sh/hook: test
  labels:
    app.kubernetes.io/instance: squadquest-supabase
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: supabase
    helm.sh/chart: supabase-0.1.3
  name: squadquest-supabase-test-kong
  namespace: squadquest-supabase
spec:
  template:
    spec:
      containers:
        - command:
            - /bin/bash
            - '-c'
            - |
              echo "Attempting to access dashboard with provided credentials..."
              curl -sL --fail \
                -o /dev/null \
                "http://${DASHBOARD_USERNAME}:${DASHBOARD_PASSWORD}@squadquest-supabase-supabase-kong:8000" \
                  || { echo -e "\033[31mFailed to connect to the squadquest-supabase-supabase-kong.\033[0m"; exit 1; }

              echo "Successfully connected."
          env:
            - name: DASHBOARD_USERNAME
              valueFrom:
                secretKeyRef:
                  key: username
                  name: dashboard
            - name: DASHBOARD_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: password
                  name: dashboard
          image: kdevup/curljq
          imagePullPolicy: IfNotPresent
          name: test-kong
      restartPolicy: Never
  ttlSecondsAfterFinished: 100
