apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app.kubernetes.io/instance: squadquest-supabase
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: supabase
    helm.sh/chart: supabase-0.1.3
  name: squadquest-supabase-supabase-db-pvc
  namespace: squadquest-supabase
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
