apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/instance: chime
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: chime
    app.kubernetes.io/version: 1.0.0
    helm.sh/chart: chime-0.1.0
  name: chime
  namespace: chime
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: http
  selector:
    app.kubernetes.io/instance: chime
    app.kubernetes.io/name: chime
  type: ClusterIP
