---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cnpg-backup-creds
  namespace: cloudnative-pg
spec:
  encryptedData:
    ACCESS_KEY_ID: AgDl1qmQyjZlUKn+J2a+6C5NXq66dDT7M94MY4KLWZVevFYvtqFJtnJAiEyx5Rzb+r0+MzNyff5Xu5B1Uj1ckVDPQTk89d6VdI0aA4xjhJH3ChCPa6AH06pJi5vWGL+TtJB8o5snQESx8D/TBy4by+lVSQL+/0OYIEfeWLodB9bUXtUzLq8cLZTmdjIJINoOW9E0LeRKORuFHrSS7fNwoVacDq091ES9gvvQlC/pyeRh2xrOyHxfYaIL5+tZ/fPFRtexrpXdx/sowpr+faquWVTo8oekHzsKY+PPbMQfjddbLhJIhQpFJ2cM2w7W1nhKNHRRziqt+anvECUMrozTpbzdYQxVD0BtNFNoESiOLoyU1ZZWSggCR9LtJt3KYNT/BdKghB+hOS+p5bDgo0WwKGoGljrNhPaYZ44j1JZ7i7WiufFp5SPMd6tDMxiX/dVKCEZuDAwpV4iBwmBQvwbeTw9UXrkhnEzlAnOj2tRMUL6RyXnTjNSmVfTQmpykKC389vgMjWQ7sUSKWiYQ2+oTCy/gVc4xOD7IJsLVyXVG3+58vLh7sl6UpCAiJj9LmfAqM+qFleFiZJYd8rvk2hY7qigrGVKNV/m8x+Gu5V2XxhOR3AmGQtncJackhphFeLe7QrBWMePha9ooWMA12H3NEg7Xh5/TEKa/tBLElR9pNql1grCr9zzZvsuMZnVUpoIr+as0ZM/PjJEJY8+ZxXeSxBHkdQjsXg==
    ACCESS_SECRET_KEY: AgDHHHC63As/z2l1RVarZqH3eT05H44bDU+24d4/SA79K3JDdNhjzLhDwhoAsnI8DKykZsjlHgYh6SPCKsy1vmC4rmQZK21mD465rl2ZTF0JdFRsn/1cHOzEt7XGPTlkyBOkcY5y7IQHuvGTRVIrGmBr4dmjEcU/u4uxycLfp73yqHYfzgSpTgGzusQvqRRw99+OlW4+4HvWbf0X8Gk1EEZJ/jMK2s+4fo1RDBEr5dP3yvShz0XxQ/RlNyJlNreOSKOYWXzMj0UxgmItgiEsu0mjn6Y7yehmgtZxFMsOd3TfKvX6ZeWjns+icvryDleY29gbVxKQXWSXQ7zjz31TJfkgrVobwj9CjVxbKGv+oE0JWhycFFA0kyAn5FmusR2+SEnBnxy9SUizx3DxWMJSGldY0n4hkd93+s6pkASUp6mRs8JSnYBaZYUWbz7Pbj/Hx9HrJrpk2X2N0w0DvgWr+T8ziI1vTcke3WfVWglNIK5PlEDUsOnB8xetQMv2jzqvhKg/YA3hYgx0AuqhpEWJPnoLghyYiFUa6VXWyHtyWQpmDrp4j/MAuDOF3os0Y7i+rfvOJKpvPfQapQFoFSctB39/UJAp1iCY7o3NzgZ4y2CdhCDHixy7Vopg1EDncAHLAZXzcoSQpeN0hhtdaSHBv4IdArjiqMWaF4Rt7NL2IVJfsz2xIOKlSNPs9XiNLGpUQETkEPbuUTZ3gwr8gcnSzGsutDYQlZdGld2v5NovyJYGHL1JYuehxyyn
  template:
    metadata:
      name: cnpg-backup-creds
      namespace: cloudnative-pg
